### ISSUE TITLE
Technique mistake in the paper

### ISSUE THREAD

**Issue by hangg7** [zqs1022/interpretableCNN#2]
Hi,

About computing p(x|T), the technique currently listed in the paper is wrong:

It's clear that you are trying to normalize all scores in a batch using softmax where **score function is the sum over masked activations**, i.e.,

![image](https://user-images.githubusercontent.com/10098306/40324367-2c963a60-5ced-11e8-90df-88ca7e811b1f.png)

however the trace operation is not correct, since it would end in

![image](https://user-images.githubusercontent.com/10098306/40324362-249ce796-5ced-11e8-8cfb-57364c038d4b.png)

Please consider the modification - it might be a minor mistake however resulting in unnecessary confusion.

**Comment by djangogo** [comment]
Hi
@cullengao , I also find this typo.
